name: hexagonal_sliding_puzzle
description: A Hexagonal Sliding Puzzle for Flutter Challenge.
version: 1.0.05+5
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  firebase_analytics: ^9.0.5
  firebase_core: 1.12.0
  firebase_database: 9.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  share_extend: ^2.0.0
  shimmer: ^2.0.0
  twitter_intent: ^1.0.0
  url_launcher: ^6.0.18
  valuable: ^0.1.0+1

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/success/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
